version: "3.8"

services:
  db:
    container_name: mysql_eicon
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eicon
